### PR TITLE
Bug 581 ray crossing with 4d coord

### PR DESCRIPTION
**Pull request by mukoki**
Test to demonstrate #581 bug and proposal to fix it

### CODE REVIEW

**Comment by dr-jts** [comment]
The fix looks good to me. Are you going to sign an ECA?

**Comment by dr-jts** [comment]
Actually I'm thinking a better fix might be to change `RayCrossingCounter.countSegment` to use ordinate values instead of coordinates.

Thoughts?  I can make a PR for this.

**Comment by mukoki** [comment]
> The fix looks good to me. Are you going to sign an ECA?

Wow, lot of ceremony. I just filled the ECA form, but I don't know how to link my commits to this document.

**Comment by mukoki** [comment]
> Actually I'm thinking a better fix might be to add a `RayCrossingCounter.countSegment` that accepts ordinate values instead of coordinates.
> 
> Thoughts? I can make a PR for this.

I think you're right. We don't really need to get coordinates with the exact coord dimension. We rather need x,y from both coordinates. In this case, you can also remove p1 and p2 coordinate creation and ring.getCoordinate(i, p1) call which is the place where the error occured.

**Comment by dr-jts** [comment]
> Wow, lot of ceremony. I just filled the ECA form, but I don't know how to link my commits to this document.

Yes, the bureaucracy is annoying.  AFAIK you can't amend this PR - you have to create another one.

**Comment by dr-jts** [comment]
Another possibility - just use `CoordinateSequence.getCoordinate`.  Pretty sure modern JVMs optimize small object creation highly, so perhaps this is performant enough to use.  Confirming this with a performance test would be good.

**Comment by mprins** [comment]
> > Wow, lot of ceremony. I just filled the ECA form, but I don't know how to link my commits to this document.
> 
> Yes, the bureaucracy is annoying. AFAIK you can't amend this PR - you have to create another one.

when you go to https://accounts.eclipse.org/legal/eca/validation/45250 you cab see that a signed commit is needed, use `git commit -a -s`

**Comment by mukoki** [comment]
> Another possibility - just use `CoordinateSequence.getCoordinate`. Pretty sure modern JVMs optimize small object creation highly, so perhaps this is performant enough to use. Confirming this with a performance test would be good.

Do you mean as I did in the commit (bf88792abecf26538e15cf9583bd95e9b8a1a825) ?
Seems to work, but probably do more work than necessary compared to your idea to just use x,y ordinates. I'll try to test the later idea. Not sure I can easily compare performance though.

**Comment by dr-jts** [comment]
> > Another possibility - just use `CoordinateSequence.getCoordinate`. Pretty sure modern JVMs optimize small object creation highly, so perhaps this is performant enough to use. Confirming this with a performance test would be good.
> 
> Do you mean as I did in the commit ([bf88792](https://github.com/locationtech/jts/commit/bf88792abecf26538e15cf9583bd95e9b8a1a825)) ?

I'm seeing that commit use `createCoordinate`?

I mean using `CoordinateSequence.getCoordinate(i)`. That results in a Coordinate being created for every access, but this should be fairly efficient.

**Comment by dr-jts** [comment]
Superceded by #589

**Pull request closed without merging**
