### PR TITLE
fix issue ##763 Add  GeoJsonReader support type LinearRing

### PR DESCRIPTION
**Pull request by mrpan**
Add  GeoJsonReader support type LinearRing

### CODE REVIEW

**Comment by dr-jts** [comment]
GeoJSON does not have a LinearRing geometry type (cf the spec [section 3.1.6](https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.6)).  So I don't think this change is appropriate.

**Comment by mrpan** [comment]
yes,Is such that，if so,LinearRing type in GeoJSON should be use type "Polygon" to parse?，but i think if Geometry has type "LinearRing" ,GeoJSONWriter or GeoJSONReader should can solve it ,

**Comment by dr-jts** [comment]
I don't think that JTS should output a GeJSON type of `LinearRing`, because it's not standard.  And so there's no point in parsing that either (since JTS is the only lib that would emit it).

What is your use case for thinking you need a GeoJSON `LinearRing`?

**Comment by mrpan** [comment]
I see the issue #763 ,That case may be seen frequently。LinearRing is indeed not standard。

**Pull request closed without merging**
