### PR TITLE
Refactor Comparable implementation for Geometry

### PR DESCRIPTION
**Pull request by bjornharrtell**
This refactor helps JSTS translation in two ways:
- Reduce circular dependency between Geometry and its subclasses
- Use sort indexes to compare classes instead of reflection

### CODE REVIEW

**Comment by lossyrob** [comment]
lgtm, @dr-jts what do you think?

**Comment by bjornharrtell** [comment]
FYI I went ahead releasing [JSTS](https://github.com/bjornharrtell/jsts) 1.0 a few months ago based on an [experimental branch of JTS](https://github.com/bjornharrtell/jts/tree/experimental) that has this patch and quite a few more (getting a bit out of control), but I still have an interest in upstreaming this patch and more (or if possible improve the translation).

**Comment by jnh5y** [comment]
@bjornharrtell would you mind adding a unit test for the Geometry comparable ordering and re-opening this PR?

I was able to use a git cherry-pick to pull the top commit back on the new master branch.  (Again, sorry for the troubles there!)

**Comment by bjornharrtell** [comment]
@jnh5y sure no problem. I do still wish to see my experimental branch obsoleted so I'll try to pick it up when possible.

**Pull request closed without merging**
