### PR TITLE
Improve wkb wkt support

### PR DESCRIPTION
**Pull request by mukoki**
Add javadoc and tests about the improvements

### CODE REVIEW

**Comment by jnh5y** [comment]
Looks like there's still a merge conflict.  Also, Michael, don't forget to sign all your commits (-s). 

@dr-jts if this is good to go, we should merge squash it to sort out the git signing thing.  (Either or Michael'll have to fuss with amending the top commit and force pushing.)

**Comment by mukoki** [comment]
OK, just found where to sign the commit from my IDE. I was not aware about this option. I hope it will be ok next time.
Unfortunately, I don't know how to merge the conflict. There is no conflict on my fork/branch (mukoki:improve-wkb-wkt-support) . Maybe because I added a modification to a file which was not yet merged.

**Comment by dr-jts** [comment]
I think you have to amend the previous commits.  Or just make a new clean branch and copy the files over from this PR, and then commit with signoff.

**Comment by dr-jts** [comment]
Can this be split into two PRs, one for WKB and one for WKT?   Easier to review then.

**Comment by dr-jts** [comment]
What is difference between this and #92 ?

**Comment by mukoki** [comment]
Hi Martin.
I'm sorry, the situation is very confusing. I did a new PR because you asked some improvements to PR #92, but 
1 - the PR seems to be merged since june, 15 (I don't know why PR 92 is still there, it let me thing that the change was still pending)
2 - As I wanted to solve the signoff problem, I created a new PR accidentally. I though it would have replaced #92 commits, but it seems that #92 has been sent for me by Hugues from his fork, so that I created a new pull request from my fork instead.
As you can see, I really have troubles with git. Now I think the only commit of interest in #92 and #207 is  https://github.com/locationtech/jts/pull/207/commits/18b63c2f968c77db944b33947b55e522dc8a085a which is supposed to be a a signed version of https://github.com/locationtech/jts/pull/207/commits/21f917f0ca487ff9a8419a84f353f4a4b195ab5d and which just add some javadoc to the way WKB and WKT are read and a few more tests for WKT reading as you  asked in PR #92.
Hope it makes sense and sorry for the trouble.

**Comment by jnh5y** [comment]
@mukoki resolved the conflicts, signed the commits, and committed it as 1d7970532e9f3cc9c15ec4705134c9ba1eee031e.

**Pull request closed without merging**
