### PR TITLE
About #273

### PR DESCRIPTION
**Pull request by ebocher**
This PR proposes a fix about the issue #273

### CODE REVIEW

**Comment by dr-jts** [comment]
I actually did some work on this in https://github.com/locationtech/jts/compare/master...dr-jts:fix-geometry-copy

I prefer the approach in my patch, since it better encapsulates the copying logic.  Can you review and see if it fixes the problem?  If so I will make a PR

**Comment by ebocher** [comment]
Thanks a lot @dr-jts 
We really appreciate your work.
A real architect's point of view.
Best regards

**Comment by dr-jts** [comment]
Thank you, @ebocher !  

So will you drop this PR in favour of one from my patch?

**Comment by ebocher** [comment]
yep sure.

**Pull request closed without merging**
