### PR TITLE
Fix inconsistency with CoordinateArraySequence using M measures

### PR DESCRIPTION
**Pull request by mukoki**
Throws exception if CoordinateArraySequence has M values and coord is just an instance of Coordinate in
CoordinateArraySequence#getCoordinate(index,coord)
This happens, for example, in PointLocation code, but this may not be the only place.
The solution in this PR is not nice (instanceof tests), but I miss a hasM() method in Coordinate class to do it more properly. Any reason why such a method has not been added with all the "measure" stuff ?

### CODE REVIEW

**Comment by dr-jts** [comment]
Are you saying that PointLocation.isOnLine will fail if a CoordinateArraySequence withM provides a Coordinate with no M?  

Or is this just an extra consistency check?  If so, it seems like it would be better done at creation time?

**Comment by dr-jts** [comment]
As for the idea of adding `Coordinate.hasM()`, that is a good idea.  I proposed a similar improvement in #329 (but slightly more indirectly, as `getDimension` and `getMeasures` - so `hasM = getMeasures == 1`

**Comment by dr-jts** [comment]
I see the Travis CI is failing because of some test code I commited to the TestBuilder.  I will fix this ASAP.

**Comment by mukoki** [comment]
As demonstrated by the unit test, PointLocation.isOnLine fails with a Geometry containing XYZM coordinates because it internally uses CoordinateArraySequence.getCoordinate(index, coord) which copy each original ordinate (including M) to a new Coordinate() (which does not support M).

**Comment by dr-jts** [comment]
And probably an even better solution is to allow creating new instances of the actual `Coordinate `subclass used by the `CoordinateSequence`.  This probably  needs to be done by a method on the CoordinateSequence interface.  

It's tempting to rely on the `Coordinate.copy()` method, but that won't work if the sequence does not have any coordinates, and it makes for slightly obscure code (i.e. copying an existing coordinate even if there is no intention to use its value).

**Comment by mukoki** [comment]
1 - Not throwing an exception for Coordinate.setM() seems acceptable to me.
2 - If we had a hasM() method in Coordinate, we could implement CoordinateArraySequence.getCoordinate(index,coord) in a more robust way, using the smallest dimension used by CoordinateSequence and by the second coord argument. Seems the option with the least side effect.
3 - Not sure if Coordinate.copy can save us : coord throwing exception is a method argument, I think we cannot change it (it is passed by PointLocation.isOnLine algo in my case). Or did I miss something ?

**Comment by dr-jts** [comment]
Another idea:  `Coordinate.setCoordinate()` handles setting the fields correctly.   And `Coordinate `ordinate accessors do not throw if an ordinate does not exist (they return NaN as per design).   So should be able to use `Coordinate.setCoordinate()` safely in `CoordinateArraySequence.getCoordinate` ?

And agreed that `Coordinate.set` methods should handle missing ordinates silently, without throwing.

**Comment by mukoki** [comment]
You mean
public void getCoordinate(int index, Coordinate coord) {
    coord.setCoordinate(coordinates[index]);
}
Seems the best idea so far ;-)

**Comment by dr-jts** [comment]
Excellent.  Surprisingly tricky to get the Coordinate subclasses right - as I expected.

**Pull request merged**
