### PR TITLE
Add Polygonal Coverage validation, gap finding, union

### PR DESCRIPTION
**Pull request by dr-jts**
Adds the package `org.locationtech.jts.coverage` containing classes for operating on Polygonal Coverages:

* `CoverageValidator` determines if a set of polygons forms a valid coverage and identifies locations of invalidity (and optionally narrow gaps) 
* `CoveragePolygonValidator` determines if a single polygons forms a valid coverage with adjacent polygons, and identifies locations of invalidity (and optionally narrow gaps) 
* `CoverageGapFinder` detects narrow gaps which form holes in a polygonal coverage
* `CoverageUnion` performs an efficient union of a set of polygons which form a coverage

_An invalid polygonal coverage with overlaps and gaps_
image

### CODE REVIEW

**Comment by micycle1** [comment]
Is a FixGaps feature (using `GeometrySnapper`?) in the works?

Also, it seems the JTS `1.20.0-SNAPSHOT` Maven artifact does not include this and later commits.

**Comment by dr-jts** [comment]
> Is a coverage FixGaps feature (ala [`CoverageCleaner`](https://github.com/openjump-gis/topology-extension/blob/main/src/main/java/com/vividsolutions/jcs/conflate/coverage/CoverageCleaner.java)) in the works?

Yes, hopefully some kind of coverage cleaning algorithm will be developed soon.

**Comment by micycle1** [comment]
> > Also, it seems the JTS `1.20.0-SNAPSHOT` Maven artifact does not include this and later commits.
> 
> Do you mean when you build locally?

The artifact that is pulled down from `https://repo.eclipse.org/content/repositories/jts-snapshots`.

**Comment by dr-jts** [comment]
> > > Also, it seems the JTS `1.20.0-SNAPSHOT` Maven artifact does not include this and later commits.
> > 
> > 
> > Do you mean when you build locally?
> 
> The artifact that is pulled down from `https://repo.eclipse.org/content/repositories/jts-snapshots`.

When I pull down the [latest SNAPSHOT archive](https://repo.eclipse.org/content/repositories/jts-snapshots/org/locationtech/jts/jts-core/1.20.0-SNAPSHOT/jts-core-1.20.0-20221011.165633-120.jar) I see the following files, which looks correct?
```
   creating: org/locationtech/jts/coverage/
  inflating: org/locationtech/jts/coverage/CoverageBoundarySegmentFinder.class  
  inflating: org/locationtech/jts/coverage/CoverageEdge.class  
  inflating: org/locationtech/jts/coverage/CoverageGapFinder.class  
  inflating: org/locationtech/jts/coverage/CoveragePolygonValidator$CoverageRingSegment.class  
  inflating: org/locationtech/jts/coverage/CoveragePolygonValidator.class  
  inflating: org/locationtech/jts/coverage/CoverageRing.class  
  inflating: org/locationtech/jts/coverage/CoverageRingEdges.class  
  inflating: org/locationtech/jts/coverage/CoverageSimplifier.class  
  inflating: org/locationtech/jts/coverage/CoverageUnion.class  
  inflating: org/locationtech/jts/coverage/CoverageValidator.class  
  inflating: org/locationtech/jts/coverage/InvalidSegmentDetector.class  
  inflating: org/locationtech/jts/coverage/TPVWSimplifier$1.class  
  inflating: org/locationtech/jts/coverage/TPVWSimplifier$Edge.class  
  inflating: org/locationtech/jts/coverage/TPVWSimplifier$EdgeIndex.class  
  inflating: org/locationtech/jts/coverage/TPVWSimplifier.class  
  inflating: org/locationtech/jts/coverage/VertexCounter.class  
```

**Comment by micycle1** [comment]
> When I pull down the [latest SNAPSHOT archive](https://repo.eclipse.org/content/repositories/jts-snapshots/org/locationtech/jts/jts-core/1.20.0-SNAPSHOT/jts-core-1.20.0-20221011.165633-120.jar) I see the following files, which looks correct?

Actually, my bad. I was looking for the features in the wrong project whose .pom was still referencing `1.19.0`..

**Pull request merged**
