### PR TITLE
Fix testrunner.sh to work with current code layout

### PR DESCRIPTION
**Pull request by strk**
See https://dev.locationtech.org/mhonarc/lists/jts-dev/msg00167.html
and https://github.com/locationtech/jts/issues/104#issuecomment-314463753

\cc @bjornharrtell

### CODE REVIEW

**Comment by bjornharrtell** [comment]
Nice! I tried and failed (with minimal effort..)

**Comment by strk** [comment]
It is very usefu for mel to be able to run the same XML test with JTS (testrunner) and with GEOS (XMLTester) for debugging discrepancies. Actually I might be the original author of that script (not sure as history was trimmed in the move from SVN to GIT - after having been trimmed in the past during the move from CVS to SVN  ...)

**Comment by bjornharrtell** [comment]
FYI the trimming was intentional to be able to re-license the code. Not saying that's entirely optimal but at least understandable.

**Comment by strk** [comment]
interesting, like cutting a dog's leash to claim ownership of it ?

**Comment by bjornharrtell** [comment]
AFAIK previous contributors have given permission for the licence change for the current code, but it was more or less impossible to verify for each historic version resulting in the decision to wipe history. But I'm not an authoritative source on the subject this is just my outside observations.

**Comment by strk** [comment]
guess I could move testrunner.sh to GEOS codebase and drop from here, as I didn't like the license change either ..

**Comment by strk** [comment]
There, moved to GEOS:
https://trac.osgeo.org/geos/changeset/b7ec17b493016dc0cf628682445e1041a2d9e096/git

The script can be removed from this repository.

**Comment by strk** [comment]
For historical reference: https://sourceforge.net/p/jts-topo-suite/code/787/log/?path=/trunk/jts/bin/testbuilder.sh

**Comment by dr-jts** [comment]
Agreed that including the original JTS scripts would be useful.

Probably they should reference the artifacts created in the module  `target `directories (although I'm no Maven expert, so I will confirm this).

I'll make an issue for this.

**Pull request closed without merging**
