### PR TITLE
Adding FAQ - try 2

### PR DESCRIPTION
**Pull request by moovida**
This PR adds the FAQ page, as discussed in issue #122

### CODE REVIEW

**Comment by lossyrob** [comment]
Nice! Thank you!

**Comment by lossyrob** [comment]
Supersedes #127

**Comment by dr-jts** [comment]
Nice to have this done.  Thanks!

**Comment by dr-jts** [comment]
One more thing that would be nice to do: style the JTS Javadoc references to make them look more like "code".  The simple way to do this is to wrap them in <tt> tags. Even better is to wrap them in a <span> with a CSS class 'javadoc' defined in the document.

**Comment by lossyrob** [comment]
@dr-jts good point. I can create a new issue for that specific styling work.

**Comment by lossyrob** [comment]
Created https://github.com/locationtech/jts/issues/133 for the continuation of this work.

**Pull request merged**
