### PR TITLE
A intersection between a very narrow polygon and bigger one seems to give wrong result with OverlayNGRobust

### PR DESCRIPTION
**Pull request by larsop**
We startet to test more on OverlayNGRobust, but then we got this case .

Input is two geometries where one is very narrow at the border of the big polygon

Screenshot 2021-11-27 at 09 57 32

The other is big a polygon

Screenshot 2021-11-27 at 09 59 44

The intersection between this should have been close to the narrow polygon like this

Screenshot 2021-11-27 at 10 01 55

But with latest master i get this which is way to big.

Screenshot 2021-11-27 at 10 03 15

Before testing  on OverlayNGRobust used our own code together with snapcode that I got you some years a go and home made code handled this case correctly. 

The difference between OverlayNGRobust master and my old code is that I try resolve MultiPolygon before I start to do the intersection, then I don't get any TopoError and do not need to do any snaping.

So I added a test OverlayMiscTest#test_7_Intersection_loop where used code like this and that seems to work

```
     for (int i = 0; i < g2.getNumGeometries(); i++) {
          Geometry g2GeoN = g2.getGeometryN(i);
          for (int y = 0; y < g1.getNumGeometries(); y++) {
              Geometry g1GeoN = g1.getGeometryN(y);
              Geometry cleanIntersection = g1GeoN.intersection(g2GeoN);
              cleanIntersection.getGeometryType();
              newGeoList.add(cleanIntersection);
          }
      }
```

But the OverlayMiscTest#test_7_Intersection_OverlayNGRobust failed 

With this [commit](https://github.com/larsop/jts/commit/585d17a1232facdcbc8aee120a1c69343cc0f5bbl) the OverlayMiscTest#test_7_Intersection_OverlayNGRobust runs through.

### CODE REVIEW

**Comment by dr-jts** [comment]
I suspect this is a similar issue to #798.  I have a fix to that issue, which consists of an additional heuristic check on the result area compared to the inputs.  That will be implemented very soon.

However, in your second case this will return a result of `POLYGON EMPTY`, due to the triggering of more aggressive snapping. As you point out, this can be improved by intersecting each polygon element separately.  But at the moment I don't want to build that in, due to complexity and performance reasons.  

How important is having a non-empty result for you?  The narrow input polygon is very small, so it seems that perhaps it's just an artifact, and doesn't matter if it's essentially discarded?

**Comment by dr-jts** [comment]
@larsop is this fixed by #812?

**Comment by dr-jts** [comment]
Should be fixed.  Closing.

**Comment by larsop** [comment]
Thanks , yes I tested with master now and it works perfect, sorry for the late replay.

**Pull request closed without merging**
