### PR TITLE
AffineTransformation.rotate uses the wrong rotationInstance method

### PR DESCRIPTION
**Pull request by zhenyanghua**

### CODE REVIEW

**Comment by dr-jts** [comment]
Good find.  A unit test for this would be great to have as well.

**Comment by dr-jts** [comment]
The unit tests look good. But the last commit doesn't look right, and it's now failing IP validation.  Can you remove the last commit?

**Comment by zhenyanghua** [comment]
That seems like an eclipse sign-off issue. any hint?

**Comment by dr-jts** [comment]
Yes, it's a sign-off issue. Did you sign off both commits?

**Comment by zhenyanghua** [comment]
I did for the first commit directly via github editor. As for the second one, I pushed through my local repo, which failed the check.

**Comment by dr-jts** [comment]
Perhaps you have not signed an ECA as describe in the [Contributing guide](https://github.com/locationtech/jts/blob/master/CONTRIBUTING.md)?

**Comment by zhenyanghua** [comment]
Well, I know that I had to amend my commit in order to do an empty push to trigger the hooks. It seems working now.

**Pull request merged**
