### PR TITLE
Updating license for GeoTools/OSGeo BSD license for contributed code

### PR DESCRIPTION
**Pull request by jnh5y**
This is in accordance with [Letter from GeoTools PMC](https://github.com/geotools/geotools/wiki/JTS-ORA-Contribution).

Signed-off-by: Jim Hughes <jnh5y@ccri.com>

### CODE REVIEW

**Comment by jnh5y** [comment]
@jodygarnett Good point about the more general language.  I updated it.  Is that sufficient or do you have some better words?

**Comment by jodygarnett** [comment]
thanks, merged now

**Comment by dr-jts** [comment]
Can we delete the branch now?

**Comment by jodygarnett** [comment]
yes, after merging branch can be deleted

**Pull request merged**
