### PR TITLE
Make STRtree use Java PriorityQueue and deprecate internal

### PR DESCRIPTION
**Pull request by bjornharrtell**
Signed-off-by: Björn Harrtell <bjorn@wololo.org>

### CODE REVIEW

**Comment by dr-jts** [comment]
Deleting the `PriorityQueue` class is a breaking change.  Is that necessary for transpilation, or could you simply blacklist it?

**Comment by bjornharrtell** [comment]
Ah, didn't realize that. I just had a quick "ah this code isn't needed anymore" thought.

It's not important for JSTS. But do you agree STRtree should use Java built in instead and that we could mark the internal one as deprecated?

**Comment by dr-jts** [comment]
Yes, makes sense to switch STRtree to the Java PQ.

**Comment by bjornharrtell** [comment]
@dr-jts reworked and ready for review.

**Pull request merged**
