### PR TITLE
JTS-Core OSGI bundle

### PR DESCRIPTION
**Pull request by ebocher**
JTS-Core cannot be used in an OSGi framework. This patch configure JTS-Core module to automatically generate OSGi manifest.

### CODE REVIEW

**Comment by jnh5y** [comment]
@ebocher, can you fill out the Eclipse Contributor Agreement?  The agreement is here (https://www.eclipse.org/legal/ECA.php and click on "Sign" on the left hand side)  and you'll need to use your email address (erwan.bocher@univ-ubs.fr) as you create the Eclipse account.

**Comment by ebocher** [comment]
Done on https://www.eclipse.org.

**Comment by jnh5y** [comment]
Hi @ebocher, I've merged this PR as 16d357f761971b5b48a08ab7cf50af4edf18dd84 on master.  I made some formatting changes and changed the hardcoded 1.15.0-SNAPSHOT to the Maven ${project.version} variable.

**Comment by ebocher** [comment]
Thanks

**Pull request closed without merging**
