### PR TITLE
Add CLI for running operations

### PR DESCRIPTION
**Pull request by dr-jts**
Add CLIs for running operations

### CODE REVIEW

**Comment by jnh5y** [comment]
@dr-jts This looks like fun, so I wanted to try it out.  

I think the testbuilderop.sh needs to reference JTSTestBuilder.jar instead of JTSTestRunner.jar.
(E.g., the last line should be...)
java -cp ${JTS_LIB_DIR}/JTSTestBuilder.jar org.locationtech.jtstest.testbuilder.cmd.TestBuilderOpCmd $@

Separate from that, can you give a quick example of using the new command line tool?

**Comment by dr-jts** [comment]
Right, that reference to JTSTestRunner.jar is a copy-paste bug.  I'll fix it very shortly

**Comment by dr-jts** [comment]
An example of running is:
```
testrunnop -op Overly.unaryUnion -afile some-file-with-geom.wkt -output wkb
```
That reads the WKT file (containing one or more geometries), executes the Overlay.unaryUnion operation (which is just a synonym for Geometry.union() in this case), and outputs the result as WKB.

**Comment by dr-jts** [comment]
One slightly confusing thing is that the -op arg has to be Category.function, which are listed in the TestBuilder Spatial Function panel tree view.  

In particular, only *some* Geometry methods are actually given under the Geometry category. So that might be bit confusing.  I think I'll add all the Geometry methods there, so that it's more obvious. I will also add a dump of the full list of function names that are available (triggered by a -help argument).

Thx for testing this out - let me know how it goes.

**Comment by dr-jts** [comment]
Updated to fix issue and add operations listing

**Pull request merged**
