### PR TITLE
Add generics to jts-core index

### PR DESCRIPTION
**Pull request by mahdilamb**
Add generics to index module. 
A few other minor changes (adding annotations)

Signed-off-by: Mahdi Lamb <mahdilamb@gmail.com>

### CODE REVIEW

**Comment by jnh5y** [comment]
@mahdilamb thanks!  Sorry for the trouble with the ECA webhook.  I can see that you've signed the ECA via Eclipse's website, so thanks for handling that part of contributing.

@dr-jts @jodygarnett I'd recommend we hold this until after the soon-ish JTS 1.18.0 release since it is a major change.  I'd kinda like to see what impact it'd have on the GeoTools project to get a sense for the change, etc.  That said, I think we can review it and approve (or not).

**Comment by mahdilamb** [comment]
Thanks @jnh5y! Sorry for polluting with so many closed pull requests. I've only targeted the spatial index in the hope that it isn't too disastrous. Let me know If I need to make any changes.

**Comment by dr-jts** [comment]
> @dr-jts @jodygarnett I'd recommend we hold this until after the soon-ish JTS 1.18.0 release since it is a major change. I'd kinda like to see what impact it'd have on the GeoTools project to get a sense for the change, etc. That said, I think we can review it and approve (or not).

Agreed, this is a pretty major change, so waiting until after 1.18 sounds like the best plan.

**Comment by dr-jts** [comment]
It is better if the various small logic changes (e.g. changing `<?` into `Math.max`etc) are put into a separate PR, for traceability.

**Comment by dr-jts** [comment]
There doesn't seem to be any changes to the internal code using the genericized classes. Is that ok?  

It would be nice to update the internal usage to use generics, to (a) validate that the generics work and (b) provide examples of how to use them.

**Comment by mahdilamb** [comment]
@dr-jts I was hoping that not changing the internals would be a bit more backwards compliant, might have a stronger bash at this at some point. When is 1.18.0 being released? I'll add test cases and separate the minor code changes. P.s. is there a secret to passing the ECA?

**Comment by dr-jts** [comment]
> @dr-jts I was hoping that not changing the internals would be a bit more backwards compliant

That is a good point, although I'm not sure how much of a concern that is.  Test cases will help to address this. Although it's always nice to "dog food" changes to the core library in internal code.

> When is 1.18.0 being released? 

By year end, hopefully.

**Comment by mahdilamb** [comment]
@dr-jts thanks for the replies. I'll have another look sometime soon :)

**Comment by mahdilamb** [comment]
I'm going to close this and open a new PR with the changes (sorry for the mess)


Mahdi

**Pull request closed without merging**
