### PR TITLE
introduce pmd and checkstyle build-tools and tone down javadoc failures

### PR DESCRIPTION
**Pull request by jodygarnett**
This pull request just adds the changes to the build chain and does not change any java code (yet).

Instructions for use are included in the DEVELOPMENT.md

### CODE REVIEW

**Comment by dr-jts** [comment]
Is this standalone?  I.e. does Maven pull in whatever it needs to run this?

**Comment by jodygarnett** [comment]
Yes maven pulls in everything needed to run this.

I set this up to run checks during the maven `verify` stage, and to produce a report if you want to run `site`. See the change to the DEVELOPING docs for details.

Aside: I control exactly what versions it pulls in using the plugin management section. In many cases we are using older plugins so I may experiment with upgrading over time.

**Comment by dr-jts** [comment]
Can this functionality be executed in Eclipse as well?

**Comment by dr-jts** [comment]
Why are the Oracle changes included in this PR?

**Comment by jodygarnett** [comment]
> Why are the Oracle changes included in this PR?

So I could compile and run tests, and then in running tests I found problems that I could fix.

**Comment by jodygarnett** [comment]
> Can this functionality be executed in Eclipse as well?

Sorry which functionality is that?
- eclipse pmd and checkstyle - if you do not install eclipse plugins for this functionality they will not produce warnings in eclipse
- eclipse javadoc warnings can be [configured](https://help.eclipse.org/2021-06/topic/org.eclipse.jdt.doc.user/reference/preferences/java/compiler/ref-preferences-javadoc.htm) it also respects the same supress warning tags as `javac` ``@SuppressWarning("unused")``

**Comment by dr-jts** [comment]
> > Can this functionality be executed in Eclipse as well?
> 
> Sorry which functionality is that?

All of the new checks.  Leaving them to PR-time is too late, and isn't easy to review fixes.

**Comment by jodygarnett** [comment]
> > > Can this functionality be executed in Eclipse as well?
> > 
> > 
> > Sorry which functionality is that?
> 
> All of the new checks. Leaving them to PR-time is too late, and isn't easy to review fixes.

Yes these same checks can be run from the IDE, if there are IDE specific build instructions we can make a note on how to do so:

* https://checkstyle.org/eclipse-cs/ use with `build-tools/src/main/resources/jts/checkstyle.xml` (and `header.txt`)
* https://eclipse-pmd.github.io use with `build-tools/src/main/resources/jts/pmd-ruleset.xml`

**Comment by jodygarnett** [comment]
I have isolated oracle pull request https://github.com/locationtech/jts/pull/766 and will rebase this PR.

**Comment by jodygarnett** [comment]
@dr-jts I installed eclipse IDE and update the instructions with some notes on how configure checkstyle and pmd integration

**Comment by jodygarnett** [comment]
okay, everything is green

**Pull request merged**
