### PR TITLE
Fix computation of MinimumBoundingCircle.farthestPoints

### PR DESCRIPTION
**Pull request by FObermaier**
relates to #520

Signed-off-by: Felix Obermaier <felix.obermaier@netcologne.de>

### CODE REVIEW

**Comment by dr-jts** [comment]
The small amount of actual code changed is obscured by all the formatting changes.  So I will make a new PR with just the relevant changes.

**Comment by dr-jts** [comment]
Superseded by #522

**Comment by FObermaier** [comment]
You can turn off whitespace comparison:
grafik

**Comment by dr-jts** [comment]
> You can turn off whitespace comparison:

Ah, good to know.  I will do this next time!  Thanks again for submitting the PR.

**Pull request closed without merging**
