### PR TITLE
Improve GeometryPrecisionReducer to handle GeometryCollections

### PR DESCRIPTION
**Pull request by dr-jts**
Improve GeometryPrecisionReducer to handle GeometryCollections.

Signed-off-by: Martin Davis <mtnclimb@gmail.com>

### CODE REVIEW

**Comment by dr-jts** [comment]
Fixes #88

**Comment by dr-jts** [comment]
Fixes #324

**Comment by mprins** [comment]
Why is this listed as an API change in te release notes? 
because it doesn't change the API of `GeometryPrecisionReducer` or `GeometryTransformer`...

**Comment by dr-jts** [comment]
> Why is this listed as an API change in te release notes?

Correct, the actual API hasn't changed. But the behaviour of `GeometryPrecisionReducer` has changed slightly.  It is less tolerant of invalid input.  See discussion in #653

**Pull request merged**
